/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package zoologico.view;

import zoologico.view.servicios.FrameCrearAnimal;
import zoologico.view.servicios.FrameEnjaularAnimal;

/**
 *
 * @author juan_
 */
public class AnimalesView extends javax.swing.JInternalFrame {

    /**
     * Creates new form Animales
     */
    public AnimalesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Texto1PanelAnimalitos = new javax.swing.JLabel();
        botonCrearAnimal = new javax.swing.JButton();
        botonEnjaularAnimal = new javax.swing.JButton();

        setBackground(new java.awt.Color(100, 8, 50));
        setBorder(new javax.swing.border.MatteBorder(null));
        setMaximizable(true);
        setResizable(true);
        setTitle("Sección Animalitos del Zoo");

        Texto1PanelAnimalitos.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        Texto1PanelAnimalitos.setText("¿Qué desea hacer?...");

        botonCrearAnimal.setBackground(new java.awt.Color(0, 255, 255));
        botonCrearAnimal.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        botonCrearAnimal.setText("Crear Animal");
        botonCrearAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearAnimalActionPerformed(evt);
            }
        });

        botonEnjaularAnimal.setBackground(new java.awt.Color(0, 255, 255));
        botonEnjaularAnimal.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        botonEnjaularAnimal.setText("Enjaular Animal");
        botonEnjaularAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnjaularAnimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Texto1PanelAnimalitos)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(botonCrearAnimal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(botonEnjaularAnimal)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Texto1PanelAnimalitos)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEnjaularAnimal)
                    .addComponent(botonCrearAnimal))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearAnimalActionPerformed
        FrameCrearAnimal frameanimal = new FrameCrearAnimal();
        frameanimal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonCrearAnimalActionPerformed

    private void botonEnjaularAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnjaularAnimalActionPerformed
        FrameEnjaularAnimal frameJaula = new FrameEnjaularAnimal();
        frameJaula.setVisible(true);
        this.dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEnjaularAnimalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Texto1PanelAnimalitos;
    private javax.swing.JButton botonCrearAnimal;
    private javax.swing.JButton botonEnjaularAnimal;
    // End of variables declaration//GEN-END:variables
}
