/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package zoologico.view;

import zoologico.view.servicios.FrameAlimentarAnimal;
import zoologico.view.servicios.FrameCrearJaulas;
import zoologico.view.servicios.FrameSubirCargarDb;
import zoologico.view.servicios.FrameVerJaulas;

/**
 *
 * @author juan_
 */
public class ZooView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ZooView
     */
    public ZooView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonVerJaulas = new javax.swing.JButton();
        botonCrearJaulas = new javax.swing.JButton();
        botonDb = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 24, 242));
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestión de el Zoo");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel1.setText("¿Qué desea hacer?...");

        botonVerJaulas.setBackground(new java.awt.Color(0, 255, 255));
        botonVerJaulas.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        botonVerJaulas.setText("Ver Jaulas");
        botonVerJaulas.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                botonVerJaulasAncestorRemoved(evt);
            }
        });
        botonVerJaulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerJaulasActionPerformed(evt);
            }
        });

        botonCrearJaulas.setBackground(new java.awt.Color(0, 255, 255));
        botonCrearJaulas.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        botonCrearJaulas.setText("Crear Jaulas");
        botonCrearJaulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearJaulasActionPerformed(evt);
            }
        });

        botonDb.setText("Base de Datos...");
        botonDb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(botonVerJaulas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCrearJaulas)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(190, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonDb)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonCrearJaulas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botonVerJaulas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(botonDb)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerJaulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerJaulasActionPerformed
        FrameVerJaulas verJaulas = new FrameVerJaulas();
        verJaulas.setVisible(true);
        this.dispose();      
    }//GEN-LAST:event_botonVerJaulasActionPerformed

    private void botonVerJaulasAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_botonVerJaulasAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVerJaulasAncestorRemoved

    private void botonCrearJaulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearJaulasActionPerformed
        FrameCrearJaulas crearJaulas = new FrameCrearJaulas();   
        crearJaulas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonCrearJaulasActionPerformed

    private void botonDbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDbActionPerformed
        FrameSubirCargarDb sbDb = new FrameSubirCargarDb();
        sbDb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonDbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearJaulas;
    private javax.swing.JButton botonDb;
    private javax.swing.JButton botonVerJaulas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
