/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package zoologico.view;

import zoologico.view.servicios.FrameAlimentarAnimal;
import zoologico.view.servicios.FrameCrearJaulas;
import zoologico.view.servicios.FrameVerJaulas;

/**
 *
 * @author juan_
 */
public class ZooView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ZooView
     */
    public ZooView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonVerJaulas = new javax.swing.JButton();
        botonAlimentar = new javax.swing.JButton();
        botonCrearJaulas = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 24, 242));
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestión de el Zoo");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel1.setText("¿Qué desea hacer?...");

        botonVerJaulas.setBackground(new java.awt.Color(0, 255, 255));
        botonVerJaulas.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        botonVerJaulas.setText("Ver Jaulas");
        botonVerJaulas.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                botonVerJaulasAncestorRemoved(evt);
            }
        });
        botonVerJaulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerJaulasActionPerformed(evt);
            }
        });

        botonAlimentar.setBackground(new java.awt.Color(0, 255, 255));
        botonAlimentar.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        botonAlimentar.setText("Alimentar Animales");
        botonAlimentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAlimentarActionPerformed(evt);
            }
        });

        botonCrearJaulas.setBackground(new java.awt.Color(0, 255, 255));
        botonCrearJaulas.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        botonCrearJaulas.setText("Crear Jaulas");
        botonCrearJaulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearJaulasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(botonVerJaulas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(botonAlimentar)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(botonCrearJaulas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVerJaulas)
                    .addComponent(botonAlimentar))
                .addGap(18, 18, 18)
                .addComponent(botonCrearJaulas)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerJaulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerJaulasActionPerformed
        FrameVerJaulas verJaulas = new FrameVerJaulas();
        verJaulas.setVisible(true);
        this.dispose();      
    }//GEN-LAST:event_botonVerJaulasActionPerformed

    private void botonVerJaulasAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_botonVerJaulasAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVerJaulasAncestorRemoved

    private void botonCrearJaulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearJaulasActionPerformed
        FrameCrearJaulas crearJaulas = new FrameCrearJaulas();   
        crearJaulas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonCrearJaulasActionPerformed

    private void botonAlimentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAlimentarActionPerformed
        FrameAlimentarAnimal alimentarAnimal = new FrameAlimentarAnimal();   
        alimentarAnimal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAlimentarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAlimentar;
    private javax.swing.JButton botonCrearJaulas;
    private javax.swing.JButton botonVerJaulas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
