package zoologico.view.servicios;
import zoologico.controller.Zoologico;
import zoologico.view.AnimalesView;
/**
 *
 * @author juan_
 */
public class FrameCrearAnimal extends javax.swing.JFrame {
    
    String animalReptiles, animalMamifero, animalVoladores, habitatAnimal, nombreAnimal, especieAnimal, alimentacionAnimal;

    /**
     * Creates new form frameCrearAnimal
     */
    public FrameCrearAnimal() {
        initComponents();
        botones = new javax.swing.ButtonGroup();
        botones.add(radioMamiferos);
        botones.add(radioReptiles);
        botones.add(radioAereos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botones = new javax.swing.ButtonGroup();
        texto1CrearAnimal = new javax.swing.JLabel();
        radioMamiferos = new javax.swing.JRadioButton();
        radioReptiles = new javax.swing.JRadioButton();
        radioAereos = new javax.swing.JRadioButton();
        varNombre = new javax.swing.JTextField();
        varEspecie = new javax.swing.JTextField();
        varTipoAlimen = new javax.swing.JTextField();
        varHabitat = new javax.swing.JTextField();
        botonCrearAnimal = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        texto2Nombre = new javax.swing.JLabel();
        texto3Especie = new javax.swing.JLabel();
        texto4Alimentacion = new javax.swing.JLabel();
        texto5Habitat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        texto1CrearAnimal.setText("Creación de Animal:");

        radioMamiferos.setText("Mamiferos");
        radioMamiferos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMamiferosActionPerformed(evt);
            }
        });

        radioReptiles.setText("Reptiles");
        radioReptiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioReptilesActionPerformed(evt);
            }
        });

        radioAereos.setText("Aereos");
        radioAereos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAereosActionPerformed(evt);
            }
        });

        varNombre.setText("Nombre");
        varNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varNombreActionPerformed(evt);
            }
        });

        varEspecie.setText("Especie");

        varTipoAlimen.setText("Tipo Alimentación");
        varTipoAlimen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varTipoAlimenActionPerformed(evt);
            }
        });

        varHabitat.setText("Habitat");

        botonCrearAnimal.setText("Crear Animal");
        botonCrearAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearAnimalActionPerformed(evt);
            }
        });

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        texto2Nombre.setText(": Nombre");

        texto3Especie.setText(": Especie");

        texto4Alimentacion.setText(": Tipo de Alimentacion");

        texto5Habitat.setText(": Habitat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(varHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(texto5Habitat))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(295, 295, 295)
                                .addComponent(botonCrearAnimal))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(texto1CrearAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(varEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(texto3Especie))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(varNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(texto2Nombre))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(varTipoAlimen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(texto4Alimentacion)))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioAereos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radioMamiferos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radioReptiles, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(botonVolver)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto1CrearAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varNombre)
                    .addComponent(texto2Nombre)
                    .addComponent(radioMamiferos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto3Especie)
                    .addComponent(radioReptiles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varTipoAlimen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto4Alimentacion)
                    .addComponent(radioAereos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto5Habitat))
                .addGap(36, 36, 36)
                .addComponent(botonCrearAnimal)
                .addGap(51, 51, 51)
                .addComponent(botonVolver)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioReptilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioReptilesActionPerformed
        if (animalVoladores!=null) {
            animalVoladores= null;
        }else if(animalMamifero!= null){
            animalMamifero= null;
        }
        animalReptiles= "Reptil";
    }//GEN-LAST:event_radioReptilesActionPerformed

    private void varNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varNombreActionPerformed

    private void varTipoAlimenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varTipoAlimenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varTipoAlimenActionPerformed

    private void radioAereosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAereosActionPerformed

        if (animalReptiles!=null) {
            animalReptiles= null;
        }else if(animalMamifero!= null){
            animalMamifero= null;
        }
        animalVoladores= "Volador";
    }//GEN-LAST:event_radioAereosActionPerformed

    private void radioMamiferosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMamiferosActionPerformed
        
        if (animalReptiles!=null) {
            animalReptiles= null;
        }else if(animalVoladores!= null){
            animalVoladores= null;
        }
        animalMamifero= "Mamifero";
    }//GEN-LAST:event_radioMamiferosActionPerformed

    private void botonCrearAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearAnimalActionPerformed
        especieAnimal= varEspecie.getText(); 
        nombreAnimal= varNombre.getText();
        alimentacionAnimal= varTipoAlimen.getText();
        habitatAnimal= varHabitat.getText(); 
        if(animalMamifero!=null){Zoologico.CrearAnimalMamifero(nombreAnimal, especieAnimal, alimentacionAnimal, habitatAnimal);
        }else if(animalReptiles!=null){Zoologico.CrearAnimalReptil(nombreAnimal, especieAnimal, alimentacionAnimal, habitatAnimal);
        }else if(animalVoladores!=null){Zoologico.CrearAnimalVolador(nombreAnimal, especieAnimal, alimentacionAnimal, habitatAnimal);}
        varEspecie.setText("");
        varNombre.setText("");
        varTipoAlimen.setText("");
        varHabitat.setText("");
    }//GEN-LAST:event_botonCrearAnimalActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        AnimalesView animalView = new AnimalesView();
        animalView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearAnimal;
    private javax.swing.JButton botonVolver;
    private javax.swing.ButtonGroup botones;
    private javax.swing.JRadioButton radioAereos;
    private javax.swing.JRadioButton radioMamiferos;
    private javax.swing.JRadioButton radioReptiles;
    private javax.swing.JLabel texto1CrearAnimal;
    private javax.swing.JLabel texto2Nombre;
    private javax.swing.JLabel texto3Especie;
    private javax.swing.JLabel texto4Alimentacion;
    private javax.swing.JLabel texto5Habitat;
    private javax.swing.JTextField varEspecie;
    private javax.swing.JTextField varHabitat;
    private javax.swing.JTextField varNombre;
    private javax.swing.JTextField varTipoAlimen;
    // End of variables declaration//GEN-END:variables
}
