package zoologico.view.servicios;
import zoologico.controller.Zoologico;
/**
 *
 * @author juan_
 */
public class FrameCrearAnimal extends javax.swing.JFrame {
    
    String animalReptiles, animalMamifero, animalVoladores, habitatAnimal, nombreAnimal, especieAnimal, alimentacionAnimal;

    /**
     * Creates new form frameCrearAnimal
     */
    public FrameCrearAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto1CrearAnimal = new javax.swing.JLabel();
        radioMamiferos = new javax.swing.JRadioButton();
        radioReptiles = new javax.swing.JRadioButton();
        radioAereos = new javax.swing.JRadioButton();
        varNombre = new javax.swing.JTextField();
        varEspecie = new javax.swing.JTextField();
        varTipoAlimen = new javax.swing.JTextField();
        varHabitat = new javax.swing.JTextField();
        botonVarNombre = new javax.swing.JButton();
        botonVarEspecie = new javax.swing.JButton();
        botonVarAlimentacion = new javax.swing.JButton();
        botonVarHabitat = new javax.swing.JButton();
        botonCrearAnimal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        texto1CrearAnimal.setText("¿Qué tipo de animal desea crear?");

        radioMamiferos.setText("Mamiferos");
        radioMamiferos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMamiferosActionPerformed(evt);
            }
        });

        radioReptiles.setText("Reptiles");
        radioReptiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioReptilesActionPerformed(evt);
            }
        });

        radioAereos.setText("Aereos");
        radioAereos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAereosActionPerformed(evt);
            }
        });

        varNombre.setText("Nombre");
        varNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varNombreActionPerformed(evt);
            }
        });

        varEspecie.setText("Especie");

        varTipoAlimen.setText("Tipo Alimentación");
        varTipoAlimen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varTipoAlimenActionPerformed(evt);
            }
        });

        varHabitat.setText("Habitat");

        botonVarNombre.setText("*");
        botonVarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVarNombreActionPerformed(evt);
            }
        });

        botonVarEspecie.setText("*");
        botonVarEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVarEspecieActionPerformed(evt);
            }
        });

        botonVarAlimentacion.setText("*");
        botonVarAlimentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVarAlimentacionActionPerformed(evt);
            }
        });

        botonVarHabitat.setText("*");
        botonVarHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVarHabitatActionPerformed(evt);
            }
        });

        botonCrearAnimal.setText("Crear Animal");
        botonCrearAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearAnimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(varHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonVarHabitat))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(varTipoAlimen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonVarAlimentacion))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botonCrearAnimal)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(texto1CrearAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(varEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botonVarEspecie))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(varNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(botonVarNombre))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(radioAereos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(radioReptiles, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(radioMamiferos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto1CrearAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioMamiferos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioReptiles)
                    .addComponent(varNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVarNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAereos)
                    .addComponent(varEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVarEspecie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varTipoAlimen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVarAlimentacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVarHabitat))
                .addGap(28, 28, 28)
                .addComponent(botonCrearAnimal)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioReptilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioReptilesActionPerformed
        animalReptiles= "Reptil";
    }//GEN-LAST:event_radioReptilesActionPerformed

    private void varNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varNombreActionPerformed

    private void varTipoAlimenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varTipoAlimenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varTipoAlimenActionPerformed

    private void radioAereosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAereosActionPerformed
        animalVoladores= "Volador";        // TODO add your handling code here:
    }//GEN-LAST:event_radioAereosActionPerformed

    private void botonVarEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVarEspecieActionPerformed
        especieAnimal= varEspecie.getText(); 
    }//GEN-LAST:event_botonVarEspecieActionPerformed

    private void botonVarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVarNombreActionPerformed
        nombreAnimal= varNombre.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_botonVarNombreActionPerformed

    private void botonVarAlimentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVarAlimentacionActionPerformed
        alimentacionAnimal= varTipoAlimen.getText();
    }//GEN-LAST:event_botonVarAlimentacionActionPerformed

    private void botonVarHabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVarHabitatActionPerformed
        habitatAnimal= varHabitat.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_botonVarHabitatActionPerformed

    private void radioMamiferosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMamiferosActionPerformed
        animalMamifero= "Mamifero";
    }//GEN-LAST:event_radioMamiferosActionPerformed

    private void botonCrearAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearAnimalActionPerformed
        if(animalMamifero!=null){Zoologico.CrearAnimalMamifero(nombreAnimal, especieAnimal, alimentacionAnimal, habitatAnimal, "koala");
        }else if(animalReptiles!=null){Zoologico.CrearAnimalReptil(nombreAnimal, especieAnimal, alimentacionAnimal, habitatAnimal, "koala");
        }else if(animalVoladores!=null){Zoologico.CrearAnimalVolador(nombreAnimal, especieAnimal, alimentacionAnimal, habitatAnimal, "koala");}
    }//GEN-LAST:event_botonCrearAnimalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearAnimal;
    private javax.swing.JButton botonVarAlimentacion;
    private javax.swing.JButton botonVarEspecie;
    private javax.swing.JButton botonVarHabitat;
    private javax.swing.JButton botonVarNombre;
    private javax.swing.JRadioButton radioAereos;
    private javax.swing.JRadioButton radioMamiferos;
    private javax.swing.JRadioButton radioReptiles;
    private javax.swing.JLabel texto1CrearAnimal;
    private javax.swing.JTextField varEspecie;
    private javax.swing.JTextField varHabitat;
    private javax.swing.JTextField varNombre;
    private javax.swing.JTextField varTipoAlimen;
    // End of variables declaration//GEN-END:variables
}
